### PR TITLE
Compile with OpenSSL 1.1.0-pre1

### PR DESCRIPTION
**Pull request by tatsuhiro-t**
OpenSSL 1.1.0 changed API name (*_SSLeay to *_OpenSSL), this patch
handles that.  It also removed RSA_FLAG_SIGN_VER.  According to thier
commit log, its purpose was backward compatibility, and it is now
completely removed from source code, and it is safe to set just 0.

### CODE REVIEW

**Comment by kazuho** [comment]
Thank you for the PR.

Can you add a guard for LibreSSL so that it would not be considered as OpenSSL 1.1.0?

FWIW LibreSSL sets [`OPENSSL_VERSION_NUMBER` to `0x20000000L`](https://github.com/libressl-portable/openbsd/blob/7a07b33b0687f52b5a4f33799c111800f3124dfc/src/lib/libssl/src/crypto/opensslv.h#L10); therefore we cannot simply check the value to be above something.

**Comment by tatsuhiro-t** [comment]
Thank you for reviewing.  So it looks like we should check that `LIBRESSL_VERSION_NUMBER` is not defined.  Damn, LibreSSL, it just makes developers life difficult ;)

**Comment by tatsuhiro-t** [comment]
Done.  @kazuho PTAL

**Comment by kazuho** [comment]
Thank you for the changes!

**Pull request merged**
